//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetBDMuretDave.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emploi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Emploi()
        {
            this.VisiteMedicales = new HashSet<VisiteMedicale>();
        }
    
        public decimal IdEmploi { get; set; }
        public decimal IdPersonne { get; set; }
        public decimal Numero { get; set; }
        public string TypeEmploi { get; set; }

        public string TypeEmploiString
        {
            get
            {
                if (TypeEmploi.Equals("0"))
                    return "Non soumis";
                else
                    return "Soumis";
            }
        }
    
        public virtual Entreprise Entreprise { get; set; }
        public virtual Personne Personne { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisiteMedicale> VisiteMedicales { get; set; }
    }
}
