//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetBDMuretDave.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ExamenRealise
    {
        public decimal idExamenReal { get; set; }

        [Required(ErrorMessage = "Libellé de l'examen est obligatoire")]
        [RegularExpression("([a-zA-Zéèàùêâ ]+)", ErrorMessage ="Le libellé ne peut pas contenir de chiffres")]
        [StringLength(50, ErrorMessage = "Le libellé ne peut pas dépasser 50 caractères")]
        public string Libelle { get; set; }

        public decimal IdTypeExamen { get; set; }
        public decimal IdVisiteMedicale { get; set; }

        [Required(ErrorMessage = "Le résultat de l'examen est obligatoire")]
        [StringLength(1000, ErrorMessage = "Le résultat ne peut pas dépasser 1000 caractères")]
        public string Resultat { get; set; }

        [Required(ErrorMessage = "La durée de l'examen est obligatoire")]
        [RegularExpression("([0-9]+)", ErrorMessage = "Le libellé ne peut contenir que des chiffres")]
        [Range(0,900, ErrorMessage ="La durée doit être comprise entre 0 et 900 minutes")]
        public decimal Duree { get; set; }

        public string DureeEnMinute
        {
            get
            {
                return Duree + " min";
            }
        }      

        public virtual TypeExaman TypeExaman { get; set; }
        public virtual VisiteMedicale VisiteMedicale { get; set; }
    }
}
